// Code generated by "callbackgen -type BOOMPRO"; DO NOT EDIT.

package indicator

import ()

func (inc *BOOMPRO) OnUpdate(cb func(k float64, d float64)) {
	inc.updateCallbacks = append(inc.updateCallbacks, cb)
}

func (inc *BOOMPRO) EmitUpdate(k float64, d float64) {
	for _, cb := range inc.updateCallbacks {
		cb(k, d)
	}
}
