---
persistence:
  redis:
    host: redis
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    # futures: true
    envVarPrefix: BINANCE

exchangeStrategies:
- on: binance
  adxstochrsi:
    symbol: ETCUSDT
    interval: 1h
    amount: 1000

    takeProfit: 15%
    stopLoss: 10%

    useAtrStopLoss: false
    useAtrTakeProfit: false
    atrWindow: 8

    ewmaInterval: 4h
    ewmaWindow: 200

    dmiWindow: 14
    adxWindow: 14

    stochrsiKWindow: 3
    stochrsiDWindow: 3
    stochrsiRsiWindow: 14
    stochrsiStochWindow: 14
sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - ETCUSDT

backtest:
  startTime: "2022-05-01"
  endTime: "2022-07-13"
  symbols:
    - ETCUSDT
  sessions: [binance]
  accounts:
    binance:
      balances:
        ETC: 10000
        USDT: 20000.0
