---
persistence:
  redis:
    host: redis
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    futures: true
    envVarPrefix: BINANCE

exchangeStrategies:
- on: binance
  trendline:
    symbol: ETHUSDT
    interval: 1h
    amount: 1000

    takeProfit: 20%
    stopLoss: 3%

    
    # Set up your stop order, this is optional
    # sometimes the stop order might decrease your total profit.
    # you can setup multiple stop,
    stops:
    # use trailing stop order
    - trailingStop:
        # callbackRate: when the price reaches -1% from the previous highest, we trigger the stop
        callbackRate: 5.1%

        # closePosition is how much position do you want to close
        closePosition: 20%

        # minProfit is how much profit you want to take.
        # if you set this option, your stop will only be triggered above the average cost.
        minProfit: 5%

        # interval is the time interval for checking your stop
        interval: 1m

        # virtual means we don't place a a REAL stop order
        # when virtual is on
        # the strategy won't place a REAL stop order, instead if watches the close price,
        # and if the condition matches, it submits a market order to close your position.
        virtual: true
sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - ETHUSDT

backtest:
  startTime: "2022-06-01"
  endTime: "2022-07-25"
  symbols:
    - ETHUSDT
  sessions: [binance]
  accounts:
    binance:
      balances:
        ETH: 10000
        USDT: 20000.0
